# Generated by Django 3.0.3 on 2020-05-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estadoVoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MisCosas.Voto'),
        ),
    ]
