# Generated by Django 3.0.3 on 2020-05-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0002_auto_20200506_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estadoVoto',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='estado',
        ),
        migrations.AddField(
            model_name='users',
            name='estadoVoto',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voto',
            name='Item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MisCosas.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MisCosas.Users'),
            preserve_default=False,
        ),
    ]
