# Generated by Django 3.0.3 on 2020-05-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0003_auto_20200506_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='Item',
            new_name='item',
        ),
    ]
