# Generated by Django 3.0.3 on 2020-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0004_auto_20200506_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='estado',
            field=models.CharField(default='', max_length=64),
        ),
    ]
