# Generated by Django 3.0.3 on 2020-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0005_voto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
