# Generated by Django 3.0.3 on 2020-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0006_alimentador_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='pagPrincipal',
            field=models.BooleanField(default=True),
        ),
    ]
