# Generated by Django 3.0.3 on 2020-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0007_alimentador_pagprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='votosTotales',
            field=models.IntegerField(default=0),
        ),
    ]
