# Generated by Django 3.0.3 on 2020-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0008_item_votostotales'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='estilo',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='users',
            name='tamañoletra',
            field=models.CharField(default='', max_length=64),
        ),
    ]
