# Generated by Django 3.0.3 on 2020-05-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0012_users_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fotoVideo',
            new_name='fotoItem',
        ),
    ]
