# Generated by Django 3.0.3 on 2020-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0013_auto_20200515_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentador',
            name='enlace',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='alimentador',
            name='nombre',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='enlace',
            field=models.CharField(default='ma', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(default='', max_length=64),
        ),
    ]
