# Generated by Django 3.0.3 on 2020-05-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0016_auto_20200520_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MisCosas.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='MisCosas'),
        ),
    ]
